# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('real_delete', models.BooleanField(default=False)),
                ('user_id', models.CharField(default='用户id', max_length=50, verbose_name='用户ID')),
                ('user_name', models.CharField(default='匿名', max_length=50, verbose_name='用户名')),
                ('user_ip', models.CharField(default='127.0.0.1', max_length=30, verbose_name='用户IP')),
                ('chat_content', models.CharField(default='空', max_length=400, verbose_name='发送的内容')),
            ],
            options={
                'verbose_name': '聊天内容',
                'verbose_name_plural': '聊天内容',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('real_delete', models.BooleanField(default=False)),
                ('user_id', models.CharField(default='用户id', max_length=50, verbose_name='用户ID')),
                ('user_name', models.CharField(default='匿名用户', max_length=50, verbose_name='用户名')),
                ('user_ip', models.CharField(default='1.1.1.1', max_length=30, verbose_name='用户IP')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
